/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    doctors: Doctor;
    departments: Department;
    branches: Branch;
    'doctor-schedules': DoctorSchedule;
    services: Service;
    'service-packages': ServicePackage;
    news: News;
    announcements: Announcement;
    'health-tips': HealthTip;
    careers: Career;
    'doctor-talks': DoctorTalk;
    'insurance-updates': InsuranceUpdate;
    'content-search-index': ContentSearchIndex;
    promotions: Promotion;
    faqs: Faq;
    tourScenes: TourScene;
    inquiries: Inquiry;
    analyticsEvents: AnalyticsEvent;
    kpiSnapshots: KpiSnapshot;
    gaReports: GaReport;
    auditLogs: AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    'doctor-schedules': DoctorSchedulesSelect<false> | DoctorSchedulesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-packages': ServicePackagesSelect<false> | ServicePackagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'health-tips': HealthTipsSelect<false> | HealthTipsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'doctor-talks': DoctorTalksSelect<false> | DoctorTalksSelect<true>;
    'insurance-updates': InsuranceUpdatesSelect<false> | InsuranceUpdatesSelect<true>;
    'content-search-index': ContentSearchIndexSelect<false> | ContentSearchIndexSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    tourScenes: TourScenesSelect<false> | TourScenesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    analyticsEvents: AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    kpiSnapshots: KpiSnapshotsSelect<false> | KpiSnapshotsSelect<true>;
    gaReports: GaReportsSelect<false> | GaReportsSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'km' | 'zh') | ('en' | 'km' | 'zh')[];
  globals: {
    siteSettings: SiteSetting;
    operationalSettings: OperationalSetting;
    navigation: Navigation;
    socialLinks: SocialLink;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    operationalSettings: OperationalSettingsSelect<false> | OperationalSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    socialLinks: SocialLinksSelect<false> | SocialLinksSelect<true>;
  };
  locale: 'en' | 'km' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'contributor';
  avatar?: (number | null) | Media;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero?:
    | {
        heading: string;
        subheading?: string | null;
        backgroundImage?: (number | null) | Media;
        ctaText?: string | null;
        ctaLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }[]
    | null;
  sections?:
    | {
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        imagePosition?: ('left' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'section';
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  name: string;
  slug: string;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specialty?: string | null;
  /**
   * DEPRECATED: Use doctor-schedules to assign doctors to departments with recurring weekly shifts.
   */
  department?: (number | null) | Department;
  phone?: string | null;
  email?: string | null;
  /**
   * 6–8 digit doctor number (e.g. 00123456).
   */
  doctorNumber: string;
  sex?: ('male' | 'female' | 'other' | 'prefer_not_to_say') | null;
  nationality?: string | null;
  positionTitle?: string | null;
  employmentStartDate?: string | null;
  employmentType?: ('full_time' | 'part_time' | 'visiting' | 'contract') | null;
  totalClinicalExperienceYears?: number | null;
  specialistExperienceYears?: number | null;
  languages?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: (number | null) | Media;
  branch: number | Branch;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  mapUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * e.g. "Open 24 hours" or "8:00 AM - 5:00 PM"
   */
  hours?: string | null;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-schedules".
 */
export interface DoctorSchedule {
  id: number;
  /**
   * Auto-generated label for easy identification in admin panel.
   */
  label?: string | null;
  doctor: number | Doctor;
  department: number | Department;
  dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  /**
   * Format: HH:mm (24-hour). Example: 08:00
   */
  startTime: string;
  /**
   * Format: HH:mm (24-hour). Example: 12:00
   */
  endTime: string;
  /**
   * Slot duration in minutes for appointment booking.
   */
  appointmentDurationMinutes?: number | null;
  room?: string | null;
  active?: boolean | null;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  department?: (number | null) | Department;
  icon?: (number | null) | Media;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-packages".
 */
export interface ServicePackage {
  id: number;
  title: string;
  slug: string;
  department?: (number | null) | Department;
  services?: (number | Service)[] | null;
  promotion?: (number | null) | Promotion;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  priceLabel?: string | null;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  validFrom?: string | null;
  validTo?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  images?: (number | Media)[] | null;
  excerpt?: string | null;
  author?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  author?: string | null;
  slug: string;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  startDate?: string | null;
  endDate?: string | null;
  isBanner?: boolean | null;
  /**
   * Hex color code (e.g. #FF5733)
   */
  bannerBackgroundColor?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-tips".
 */
export interface HealthTip {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  author?: string | null;
  slug: string;
  healthTipCategory?: ('nutrition' | 'exercise' | 'mentalHealth' | 'preventiveCare' | 'chronicDisease') | null;
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null;
  healthTipTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  author?: string | null;
  slug: string;
  position: string;
  careerDepartment?: (number | null) | Department;
  careerLocation?: (number | null) | Branch;
  careerEmploymentType?: ('full_time' | 'part_time' | 'contract' | 'visiting') | null;
  experienceLevel?: ('entry' | 'mid' | 'senior') | null;
  salaryRange?: string | null;
  applicationDeadline?: string | null;
  careerRequirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-talks".
 */
export interface DoctorTalk {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  author?: string | null;
  slug: string;
  featuredDoctor: number | Doctor;
  talkTopic: string;
  eventDate: string;
  /**
   * Time of the talk (e.g. 14:00 - 16:00)
   */
  eventTime?: string | null;
  /**
   * Duration in minutes
   */
  duration?: number | null;
  isVirtual?: boolean | null;
  meetingLink?: string | null;
  maxAttendees?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insurance-updates".
 */
export interface InsuranceUpdate {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  excerpt?: string | null;
  author?: string | null;
  slug: string;
  coverageDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  insuranceContactPerson?: string | null;
  insuranceContactPhone?: string | null;
  insuranceContactEmail?: string | null;
  effectiveDate?: string | null;
  expirationDate?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-search-index".
 */
export interface ContentSearchIndex {
  id: number;
  sourceCollection: string;
  sourceId: string;
  contentType: string;
  locale: string;
  title: string;
  slug: string;
  canonicalPath: string;
  excerpt?: string | null;
  bodyText?: string | null;
  thumbnail?: (number | null) | Media;
  status?: string | null;
  publishedAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'appointments' | 'services' | 'insurance' | 'other') | null;
  order?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourScenes".
 */
export interface TourScene {
  id: number;
  sceneNumber: number;
  branch?: (number | null) | Branch;
  /**
   * Optional. Scenes with the same group are shown together as sub-rooms (e.g. "OPD"). Leave blank for a standalone room.
   */
  roomGroup?: string | null;
  title: string;
  description?: string | null;
  thumbnailImage?: (number | null) | Media;
  hotspots?:
    | {
        pitch: number;
        yaw: number;
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  phone?: string | null;
  email: string;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  assignedTo?: (number | null) | User;
  resolvedAt?: string | null;
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsEvents".
 */
export interface AnalyticsEvent {
  id: number;
  event:
    | 'page_view'
    | 'tour_view'
    | 'tour_scene_view'
    | 'doctor_click'
    | 'inquiry_submit'
    | 'language_switch'
    | 'call_click'
    | 'map_interaction';
  slug?: string | null;
  locale?: string | null;
  scene?: number | null;
  sessionId?: string | null;
  ipHash?: string | null;
  referrer?: string | null;
  userAgent?: string | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpiSnapshots".
 */
export interface KpiSnapshot {
  id: number;
  date: string;
  metric:
    | 'calls'
    | 'inquiries'
    | 'tour_views'
    | 'tour_sessions'
    | 'tour_scene_views'
    | 'page_views'
    | 'doctor_views'
    | 'department_views'
    | 'language_split'
    | 'doctor_clicks'
    | 'map_interactions';
  value: number;
  locale?: string | null;
  granularity: 'day' | 'week' | 'month';
  breakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gaReports".
 */
export interface GaReport {
  id: number;
  reportType: 'page_views' | 'traffic_sources' | 'user_demographics' | 'device_breakdown';
  dateRange: {
    start: string;
    end: string;
  };
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fetchedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: number;
  action: 'created' | 'updated' | 'published' | 'archived' | 'deleted';
  collectionSlug: string;
  documentId: string;
  documentTitle?: string | null;
  userId?: string | null;
  userName?: string | null;
  userRole?: ('admin' | 'editor' | 'contributor') | null;
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'doctor-schedules';
        value: number | DoctorSchedule;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-packages';
        value: number | ServicePackage;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'health-tips';
        value: number | HealthTip;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'doctor-talks';
        value: number | DoctorTalk;
      } | null)
    | ({
        relationTo: 'insurance-updates';
        value: number | InsuranceUpdate;
      } | null)
    | ({
        relationTo: 'content-search-index';
        value: number | ContentSearchIndex;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'tourScenes';
        value: number | TourScene;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'analyticsEvents';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'kpiSnapshots';
        value: number | KpiSnapshot;
      } | null)
    | ({
        relationTo: 'gaReports';
        value: number | GaReport;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaText?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  sections?:
    | T
    | {
        section?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  specialty?: T;
  department?: T;
  phone?: T;
  email?: T;
  doctorNumber?: T;
  sex?: T;
  nationality?: T;
  positionTitle?: T;
  employmentStartDate?: T;
  employmentType?: T;
  totalClinicalExperienceYears?: T;
  specialistExperienceYears?: T;
  languages?:
    | T
    | {
        name?: T;
        id?: T;
      };
  education?:
    | T
    | {
        description?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  branch?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  address?: T;
  phone?: T;
  email?: T;
  mapUrl?: T;
  image?: T;
  hours?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-schedules_select".
 */
export interface DoctorSchedulesSelect<T extends boolean = true> {
  label?: T;
  doctor?: T;
  department?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  appointmentDurationMinutes?: T;
  room?: T;
  active?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  department?: T;
  icon?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-packages_select".
 */
export interface ServicePackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  services?: T;
  promotion?: T;
  description?: T;
  image?: T;
  priceLabel?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  thumbnail?: T;
  images?: T;
  excerpt?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  thumbnail?: T;
  excerpt?: T;
  author?: T;
  slug?: T;
  priority?: T;
  startDate?: T;
  endDate?: T;
  isBanner?: T;
  bannerBackgroundColor?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-tips_select".
 */
export interface HealthTipsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  thumbnail?: T;
  excerpt?: T;
  author?: T;
  slug?: T;
  healthTipCategory?: T;
  readingTime?: T;
  healthTipTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  thumbnail?: T;
  excerpt?: T;
  author?: T;
  slug?: T;
  position?: T;
  careerDepartment?: T;
  careerLocation?: T;
  careerEmploymentType?: T;
  experienceLevel?: T;
  salaryRange?: T;
  applicationDeadline?: T;
  careerRequirements?: T;
  responsibilities?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-talks_select".
 */
export interface DoctorTalksSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  thumbnail?: T;
  excerpt?: T;
  author?: T;
  slug?: T;
  featuredDoctor?: T;
  talkTopic?: T;
  eventDate?: T;
  eventTime?: T;
  duration?: T;
  isVirtual?: T;
  meetingLink?: T;
  maxAttendees?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insurance-updates_select".
 */
export interface InsuranceUpdatesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  thumbnail?: T;
  excerpt?: T;
  author?: T;
  slug?: T;
  coverageDetails?: T;
  insuranceContactPerson?: T;
  insuranceContactPhone?: T;
  insuranceContactEmail?: T;
  effectiveDate?: T;
  expirationDate?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-search-index_select".
 */
export interface ContentSearchIndexSelect<T extends boolean = true> {
  sourceCollection?: T;
  sourceId?: T;
  contentType?: T;
  locale?: T;
  title?: T;
  slug?: T;
  canonicalPath?: T;
  excerpt?: T;
  bodyText?: T;
  thumbnail?: T;
  status?: T;
  publishedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  validFrom?: T;
  validTo?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourScenes_select".
 */
export interface TourScenesSelect<T extends boolean = true> {
  sceneNumber?: T;
  branch?: T;
  roomGroup?: T;
  title?: T;
  description?: T;
  thumbnailImage?: T;
  hotspots?:
    | T
    | {
        pitch?: T;
        yaw?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  status?: T;
  assignedTo?: T;
  resolvedAt?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsEvents_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  event?: T;
  slug?: T;
  locale?: T;
  scene?: T;
  sessionId?: T;
  ipHash?: T;
  referrer?: T;
  userAgent?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpiSnapshots_select".
 */
export interface KpiSnapshotsSelect<T extends boolean = true> {
  date?: T;
  metric?: T;
  value?: T;
  locale?: T;
  granularity?: T;
  breakdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gaReports_select".
 */
export interface GaReportsSelect<T extends boolean = true> {
  reportType?: T;
  dateRange?:
    | T
    | {
        start?: T;
        end?: T;
      };
  data?: T;
  fetchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentTitle?: T;
  userId?: T;
  userName?: T;
  userRole?: T;
  changedFields?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  logo?: (number | null) | Media;
  siteName: string;
  tagline?: string | null;
  emergencyCTAText?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operationalSettings".
 */
export interface OperationalSetting {
  id: number;
  analyticsReportRecipients?:
    | {
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  webhookTargets?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenuItems?:
    | {
        label: string;
        url: string;
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerMenuItems?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks".
 */
export interface SocialLink {
  id: number;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  siteName?: T;
  tagline?: T;
  emergencyCTAText?: T;
  contactEmail?: T;
  contactPhone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operationalSettings_select".
 */
export interface OperationalSettingsSelect<T extends boolean = true> {
  analyticsReportRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  webhookTargets?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenuItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  footerMenuItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  facebook?: T;
  instagram?: T;
  youtube?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}