- generic [active] [ref=e1]:
  - main [ref=e3]:
    - img "Next.js logo" [ref=e4]
    - generic [ref=e5]:
      - heading "To get started, edit the page.tsx file." [level=1] [ref=e6]
      - paragraph [ref=e7]:
        - text: Looking for a starting point or more instructions? Head over to
        - link "Templates" [ref=e8] [cursor=pointer]:
          - /url: https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app
        - text: or the
        - link "Learning" [ref=e9] [cursor=pointer]:
          - /url: https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app
        - text: center.
    - generic [ref=e10]:
      - link "Vercel logomark Deploy Now" [ref=e11] [cursor=pointer]:
        - /url: https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app
        - img "Vercel logomark" [ref=e12]
        - text: Deploy Now
      - link "Documentation" [ref=e13] [cursor=pointer]:
        - /url: https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app
  - alert [ref=e14]